### ISSUE TITLE
Clustering test fails

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/veniq#35]
======================================================================
FAIL: test_article (test.clustering.test_clustering.ClusteringTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\veniq\test\clustering\test_clustering.py", line 47, in test_article
    self.assertEqual(SEMI(self.example),
AssertionError: Lists differ: [[26, 34], [3, 12], [30, 31], [30, 34], [3, 25], [13, 25], [13, 22], [3, 34]] != [[26, 34], [13, 25], [3, 25], [13, 22], [3, 12], [30, 31], [30, 34], [3, 34]]

First differing element 1:
[3, 12]
[13, 25]

- [[26, 34], [3, 12], [30, 31], [30, 34], [3, 25], [13, 25], [13, 22], [3, 34]]
+ [[26, 34], [13, 25], [3, 25], [13, 22], [3, 12], [30, 31], [30, 34], [3, 34]] : Wrong unique clusters

Ran 66 tests in 0.809s

**Comment by aravij** [comment]
This test is gone. Closing issue as obsolete.
