### ISSUE TITLE
ASTNode test fails

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/veniq#37]
======================================================================
FAIL: test_class_computed_fields (test.ast_framework.test_ast_node.ASTNodeTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\veniq\test\ast_framework\test_ast_node.py", line 22, in test_class_computed_fields
    self.assertEqual(java_class.documentation, "/**\n* Some documentation\n*/")
AssertionError: '/**\r\n* Some documentation\r\n*/' != '/**\n* Some documentation\n*/'
- /**
?    -
+ /**
- * Some documentation
?                     -
+ * Some documentation
  */

**Comment by aravij** [comment]
Was solved in #48 
Closing as obsolete.
